#!/usr/bin/env bash
# set -x             # for debug
set -euo pipefail  # fail early

VIMRC=vimrc

main(){
    cat <<-EOF > $VIMRC
" ========================================================
" Generated by stripping my original config file.
" No plugin/plugin manager support.
EOF

    sed '/" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^/q' init.vim >> $VIMRC
}

main "$@"
