terminal:
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    selection: null
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  fontSize: 22
  environment: {}
  ligatures: true
  cursor: block
  alwaysUseWorkingDirectory: false
  pasteOnMiddleClick: false
  rightClick: menu
  autoOpen: true
  bracketedPaste: false
  copyOnSelect: true
  frontend: xterm
  background: theme
hotkeys:
  shell: {}
  profile: {}
  toggle-window: []
  split-right:
    - - Ctrl-Shift-Enter
  split-bottom:
    - - Ctrl-Alt-Enter
  pane-nav-left:
    - - Ctrl-Alt-Left
    - - Ctrl-Shift-H
  pane-nav-right:
    - - Ctrl-Alt-Right
    - - Ctrl-Shift-L
  pane-nav-down:
    - - Ctrl-Alt-Down
    - - Ctrl-Shift-J
  pane-nav-up:
    - - Ctrl-Alt-Up
    - - Ctrl-Shift-K
  pane-maximize:
    - - Ctrl-Enter
  next-tab:
    - - Ctrl-Shift-Right
    - - Ctrl-PageDown
  previous-tab:
    - - Ctrl-Shift-Left
    - - Ctrl-PageUp
  close-pane:
    - - Ctrl-Shift-X
  new-window: []
  toggle-last-tab:
    - - Ctrl-Space
  serial: []
serial: {}
ssh:
  warnOnClose: true
appearance:
  frame: native
  opacity: 1
  vibrancy: false
  tabsLocation: bottom
  dock: 'off'
  theme: Compact
enableWelcomeTab: false
pluginBlacklist: []
saveOutput: {}
